name: Deploy Infra

on: push

env:
  AWS_REGION: ap-south-1
  IAM_ROLE: arn:aws:iam::160071257600:role/dnitros-iac-lab-github-actions-role

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@2ec54502e3e7b5d9591613811da6daded35caa19
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get aws identity
        run: |
          aws sts get-caller-identity

      - name: Terraform Init
        run: terraform -chdir=session-6_terraform_cloud_and_pipelines init

      - name: Terraform Plan
        run: terraform -chdir=session-6_terraform_cloud_and_pipelines plan -var-file=dev.tfvars

      - name: Terraform Apply
        run: terraform -chdir=session-6_terraform_cloud_and_pipelines apply -var-file=dev.tfvars -auto-approve
